### ISSUE TITLE
CoinJoin into spawn wallet

### ISSUE THREAD

**Issue by ghost** [PulpCattel/Spawn#3]
Alternatively to sending into the spawn wallet manually, it is possible to do a Coinjoin from the `main` wallet, directly into the `spawn` wallet. Not sure if this is useful for the case of this repo, as it wants to remove the mixing from the `main` wallet history... 

Just a thought.

**Comment by PulpCattel** [comment]
Yes, my goal with Spawn is to keep the main/s wallet clean, but of course everyone can do what he wants.
An hack to achieve what you are describing would be as follow:
* Launch Spawn putting destination as your main wallet, don't deposit any fund.
* Rename spawned.json to "something else"
* Rename main wallet to `spawned.json` 
* Change `destination` setting to "something else"
* Launch Spawn

This would mix directly into spawned. When you are done, revert the name back.
This would be an hack because the unused addresses shown in the CLI would be the wrong ones. Spawn use the `receiving_addresses.txt` file to establish the addresses and this is done at wallet creation.

**Comment by ghost** [comment]
I see - that's a nice hack around it - good enough!
As you say, the reason for spawn is a different one. [closing...]
